### ISSUE TITLE
Look into ROS integration

### ISSUE THREAD

**Issue by omc8db** [MissouriMRDT/AutonomyBoard_Software#10]

**Comment by omc8db** [comment]
Potential benefits
* Simulation
* Logging
* Easier access to SLAM algorithms

Potential pitfalls
* ROS is waaay more complicated than it needs to be
* ROS is heavy
* ROS is a pain in the ass to get running on a Pi
* ROS introduces a single point of failure
* ROS distributes configuration across a bunch of different scripts, files and environment variables

**Comment by sdlouhy** [comment]
[here's](http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Kinetic%20on%20the%20Raspberry%20Pi) a source for getting kinetic working on a pi.  it can be upgraded to lunar, but i've only managed to get it to work with roscomm
