### ISSUE TITLE
Implement an updated Marker vs. Gate Detection System

### ISSUE THREAD

**Issue by declan34** [MissouriMRDT/AutonomyBoard_Software#109]
The last 4 legs are described in the rules as "For the second set of 4 posts/gates, teams will be provided with GNSS coordinates that
are within the vicinity of the posts (increasing in range from 5-20 m, approximately)" so we need to modify navigating.py or the approaching states to check more thoroughly if a marker is a gate or just a single marker.

**Comment by Byrdman32** [comment]
Make it so that navigating.py can figure out if we are about to reach a marker or gate.
