### ISSUE TITLE
Tilt compensation

### ISSUE THREAD

**Issue by omc8db** [MissouriMRDT/AutonomyBoard_Software#18]
Scale magnetometer x and y with gyroscope's tilt magnitude to compensate for slopes

**Comment by captainabedabes** [comment]
[Magnometer Tilt Compensation.pptx](https://github.com/MST-MRDT/AutonomyBoard-Software/files/1366436/Magnometer.Tilt.Compensation.pptx)

Short presentation to show math behind tilt compensation

**Comment by skeltonn** [comment]
Resolved through the use of quaternion.py
